routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home');
Route::get('page', 'PageController@index')->name('page');
Route::post('ads', 'PageController@ads')->name('ads');
Route::post('message', 'PageController@message')->name('message');
Route::post('subscribe', 'PageController@subscribe')->name('subscribe');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::post('roles/grid', 'RoleController@grid');
    Route::resource('roles','RoleController');
    Route::post('users/grid', 'UserController@grid');
    Route::resource('users','UserController');
    Route::post('products/grid', 'ProductController@grid');
    Route::resource('products','ProductController');
});

app/Models/Product/Product.php
<?php

namespace App\Models\Product;

use App\Models\Model;
use App\Models\Logs;

use Carbon\Carbon;

class Product extends Model
{
    protected $table = 'trans_product';

    protected $fillable = [
        'name', 'detail'
    ];

    public function logs()
	{
		return $this->morphMany(Logs::class, 'trans');
	}

    public function simpan($request)
    {
        $this->fill($request->all());
        $this->save();

        $log['action'] = 'create';
        $log['request'] = json_encode($request->all());
        $log['logged_date'] = Carbon::now()->format('Y-m-d h:i:s');
        $log['logged_by'] = auth()->user()->id;
        $save = new Logs;
        $save->fill($log);
        $this->logs()->save($save);
    }

    public function ubah($request)
    {
        $this->fill($request->all());
        $this->save();

        $log['action'] = 'update';
        $log['request'] = json_encode($request->all());
        $log['logged_date'] = Carbon::now()->format('Y-m-d h:i:s');
        $log['logged_by'] = auth()->user()->id;
        $save = new Logs;
        $save->fill($log);
        $this->logs()->save($save);
    }

    public function hapus()
    {
        $log['action'] = 'delete';
        $log['request'] = '-';
        $log['logged_date'] = Carbon::now()->format('Y-m-d h:i:s');
        $log['logged_by'] = auth()->user()->id;
        $save = new Logs;
        $save->fill($log);
        $this->logs()->save($save);

        $this->delete();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product\Product;
use Illuminate\Http\Request;
use App\Http\Requests\Product\ProductRequest;

use DataTables;

class ProductController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:product-list|product-create|product-edit|product-delete', ['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);

        $this->setPageTitle('Product');
        $this->setTitle('Product');
        $this->setSubtitle('');
        $this->setBreadcrumb(['Product' => '#']);
        $this->setPageLink( url('products') );

        $this->setTableStruct([
            [
			    'data' => 'num',
			    'name' => 'num',
			    'label' => '#',
			    'orderable' => false,
                'searchable' => false,
                'class' => 'text-center',
                'width' => '5%'
			],
            [
			    'data' => 'name',
			    'name' => 'name',
			    'label' => 'Name',
			    'searchable' => false,
			    'sortable' => true
			],
            [
                'data' => 'detail',
                'name' => 'detail',
                'label' => 'Detail',
                'searchable' => false,
                'sortable' => true
            ],
            [
                'data' => 'created',
                'name' => 'created',
                'label' => 'Created',
                'searchable' => false,
                'sortable' => false,
                'width' => '15%'
            ],
            [
			    'data' => 'action',
			    'name' => 'action',
			    'label' => 'Action',
			    'searchable' => false,
                'sortable' => false,
                'class' => 'text-center',
                'width' => '10%'
			]
        ]);
    }
    
    public function grid(Request $request)
    {
        $records = Product::select('*');

        // Init Sort
        if (!isset(request()->order[0]['column'])) {
            $records->orderBy('id', 'desc');
        }

        // Filters
        if ($name = $request->name) {
            $records->where('name', 'like', '%' . $name . '%');
        }
        if ($detail = $request->detail) {
            $records->where('detail', 'like', '%' . $detail . '%');
        }

        return Datatables::of($records)
                ->addColumn('num', function ($record) use ($request) {
                    return $request->get('start');
                })
                ->addColumn('created', function ($record) use ($request) {
                    $str = '<i class="fa fa-user" title="Creator" data-toggle="tooltip"></i> ' . $record->entryBy() . '<br><i class="fa fa-clock-o" title="Created time" data-toggle="tooltip"></i> ' . $record->created_at->diffForHumans();
                    return $str;
                })
                ->addColumn('action', function ($record) {
                    $btn = '';

                    //Detail
                    $btn .= $this->makeButton([
                        'type' => 'show-page',
                        'id' => $record->id,
                        'datas' => ['url' => route('products.show',$record->id)]
                    ]);

                    //Edit
                    $btn .= $this->makeButton([
                        'type' => 'edit-page',
                        'id' => $record->id,
                        'datas' => ['url' => route('products.edit',$record->id)]
                    ]);

                    // Delete
                    $btn .= $this->makeButton([
                        'type' => 'delete',
                        'id'   => $record->id,
                        'datas' => ['url' => route('products.destroy',$record->id)]
                    ]);

                    return $btn;
                })
                ->rawColumns(['created', 'action'])
                ->make(true);
    }
    
    public function index()
    {        
        return $this->render('modules.products.index', [
            'mockup' => false
        ]);
    }

    public function create()
    {
        $this->setTitle('Create Product');
        $this->pushBreadcrumb(['Create Product' => '#']);
        return $this->render('modules.products.create');
    }

    public function store(ProductRequest $request)
    {
        $product = new Product;
        $product->simpan($request);

        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }

    public function show(Product $product)
    {
        $this->setTitle('Detail Product');
        $this->pushBreadcrumb(['Detail Product' => '#']);
        return $this->render('modules.products.show', [
            'product' => $product
        ]);
    }

    public function edit(Product $product)
    {
        $this->setTitle('Change Product');
        $this->pushBreadcrumb(['Change Product' => '#']);
        return $this->render('modules.products.edit', [
            'product' => $product
        ]);
    }

    public function update(ProductRequest $request, Product $product)
    {
        $product->ubah($request);

        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }

    public function destroy(Product $product)
    {
        $product->hapus();

        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }
}

resources/views/modules/products/create.blade.php
@extends('layouts.page')

@section('form')
@if($errors->any())
<div class="callout callout-danger error-message">
  <h4>Whoops!</h4>
  There were some problems with your input : 
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
  @csrf
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('name') has-error @enderror">
        <label>Name:</label>
        <input type="text" name="name" class="form-control required" placeholder="Name" value="{{ old('name') }}">
        @error('name')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('detail') has-error @enderror">
        <label>Detail:</label>
        <textarea class="form-control required" style="height:150px" name="detail" placeholder="Detail">{{ old('detail') }}</textarea>
        @error('detail')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
      <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
    </div>
  </div>
</form>
@endsection

resources/views/modules/products/edit.blade.php
@extends('layouts.page')

@section('form')
@if($errors->any())
<div class="callout callout-danger error-message">
  <h4>Whoops!</h4>
  There were some problems with your input : 
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
  @csrf
  @method('PUT')
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('name') has-error @enderror">
        <label>Name:</label>
        <input type="text" name="name" class="form-control required" placeholder="Name" value="{{ $product->name }}">
        @error('name')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('detail') has-error @enderror">
        <label>Detail:</label>
        <textarea class="form-control required" style="height:150px" name="detail" placeholder="Detail">{{ $product->detail }}</textarea>
        @error('detail')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
      <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
    </div>
  </div>
</form>
@endsection

resources/views/modules/products/index.blade.php
@extends('layouts.grid')

@section('filter')
<div class="form-group">
  <input type="text" name="filter[name]" class="form-control" placeholder="Name" title="Name" data-toggle='tooltip'>
</div>
<div class="form-group">
  <input type="text" name="filter[detail]" class="form-control" placeholder="Detail" title="Detail" data-toggle='tooltip'>
</div>
<button type="reset" class="btn btn-default btn-flat btn-reset" title="Reset" data-toggle='tooltip'><i class="fa fa-refresh"></i></button>
<button type="button" class="btn btn-primary btn-flat btn-search" title="Search" data-toggle='tooltip'><i class="fa fa-search"></i></button>
@can('product-create')
<button type="button" class="btn btn-primary btn-flat pull-right btn-create-page" data-url="{{ route('products.create') }}" title="Create" data-toggle='tooltip'><i class="fa fa-plus"></i> Create Product</button>
@endcan
@endsection

@section('js-filters')
    d.name = $("input[name='filter[name]']").val();
    d.detail = $("input[name='filter[detail]']").val();
@endsection

resources/views/modules/products/show.blade.php
@extends('layouts.page')

@section('form')
@if($errors->any())
<div class="callout callout-danger error-message">
  <h4>Whoops!</h4>
  There were some problems with your input : 
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('name') has-error @enderror">
        <strong>Name:</strong>
        <input type="text" name="name" class="form-control" placeholder="Name" value="{{ $product->name }}" readonly>
        @error('name')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('detail') has-error @enderror">
        <strong>Detail:</strong>
        <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail" readonly>{{ $product->detail }}</textarea>
        @error('detail')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
    </div>
  </div>
@endsection