routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home');
Route::get('page', 'PageController@index')->name('page');
Route::post('ads', 'PageController@ads')->name('ads');
Route::post('message', 'PageController@message')->name('message');
Route::post('subscribe', 'PageController@subscribe')->name('subscribe');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::post('roles/grid', 'RoleController@grid');
    Route::resource('roles','RoleController');
    Route::post('users/grid', 'UserController@grid');
    Route::resource('users','UserController');
    Route::post('products/grid', 'ProductController@grid');
    Route::resource('products','ProductController');
});

app/Models/Role.php
<?php

namespace App\Models;

use Spatie\Permission\Models\Role as SpatieRole;
use App\Models\Traits\Utilities;
use App\Models\Logs;

use Carbon\Carbon;
use DB;

class Role extends SpatieRole
{
    use Utilities;

    public function logs()
	{
		return $this->morphMany(Logs::class, 'trans');
	}

    public function perms()
    {
        return DB::table("sys_role_has_permission")->where("sys_role_has_permission.role_id",$this->id)
            ->pluck('sys_role_has_permission.permission_id','sys_role_has_permission.permission_id')
            ->all();
    }

    public function isDeleteable()
    {
        if ($this->users()->count() > 0) {
            return false;
        }

        return true;
    }

    public function simpan($request)
    {
        $this->fill(['name'=>$request->input('name')]);
        $this->save();
        $this->syncPermissions($request->input('permission'));

        $log['action'] = 'create';
        $log['request'] = json_encode($request->all());
        $log['logged_date'] = Carbon::now()->format('Y-m-d h:i:s');
        $log['logged_by'] = auth()->user()->id;
        $save = new Logs;
        $save->fill($log);
        $this->logs()->save($save);
    }

    public function ubah($request)
    {
        $this->fill(['name'=>$request->input('name')]);
        $this->save();
        DB::table('sys_role_has_permission')->where('role_id', $this->id)->delete();
        $this->syncPermissions($request->input('permission'));

        $log['action'] = 'update';
        $log['request'] = json_encode($request->all());
        $log['logged_date'] = Carbon::now()->format('Y-m-d h:i:s');
        $log['logged_by'] = auth()->user()->id;
        $save = new Logs;
        $save->fill($log);
        $this->logs()->save($save);
    }

    public function hapus()
    {
        $log['action'] = 'delete';
        $log['request'] = '-';
        $log['logged_date'] = Carbon::now()->format('Y-m-d h:i:s');
        $log['logged_by'] = auth()->user()->id;
        $save = new Logs;
        $save->fill($log);
        $this->logs()->save($save);

        $this->delete();
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use App\Http\Requests\Role\RoleRequest;

use DataTables;

class RoleController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);

        $this->setPageTitle('Role');
        $this->setTitle('Role');
        $this->setSubtitle('');
        $this->setBreadcrumb(['Role' => '#']);
        $this->setPageLink( url('roles') );

        $this->setTableStruct([
            [
			    'data' => 'num',
			    'name' => 'num',
			    'label' => '#',
			    'orderable' => false,
                'searchable' => false,
                'class' => 'text-center',
                'width' => '5%'
			],
            [
			    'data' => 'name',
			    'name' => 'name',
			    'label' => 'Name',
			    'searchable' => false,
			    'sortable' => true
			],
            [
			    'data' => 'action',
			    'name' => 'action',
			    'label' => 'Action',
			    'searchable' => false,
                'sortable' => false,
                'class' => 'text-center',
                'width' => '10%'
			]
        ]);
    }

    public function grid(Request $request)
    {
        $records = Role::select('*');

        // Init Sort
        if (!isset(request()->order[0]['column'])) {
            $records->orderBy('id', 'desc');
        }

        // Filters
        if ($name = $request->name) {
            $records->where('name', 'like', '%' . $name . '%');
        }

        return Datatables::of($records)
                ->addColumn('num', function ($record) use ($request) {
                    return $request->get('start');
                })
                ->addColumn('action', function ($record) {
                    $btn = '';

                    //Detail
                    $btn .= $this->makeButton([
                        'type' => 'show-page',
                        'id' => $record->id,
                        'datas' => ['url' => route('roles.show',$record->id)]
                    ]);

                    //Edit
                    $btn .= $this->makeButton([
                        'type' => 'edit-page',
                        'id' => $record->id,
                        'datas' => ['url' => route('roles.edit',$record->id)]
                    ]);

                    if ($record->isDeleteable()) {
                        // Delete
                        $btn .= $this->makeButton([
                            'type' => 'delete',
                            'id'   => $record->id,
                            'datas' => ['url' => route('roles.destroy',$record->id)]
                        ]);
                    }

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
    }

    public function index(Request $request)
    {
        return $this->render('modules.roles.index', [
            'mockup' => false
        ]);
    }

    public function create()
    {
        $permission = Permission::allPermission();
        $this->setTitle('Create Role');
        $this->pushBreadcrumb(['Create Role' => '#']);
        return $this->render('modules.roles.create', [
            'permission' => $permission
        ]);
    }

    public function store(RoleRequest $request)
    {
        $role = new Role;
        $role->simpan($request);

        return redirect()->route('roles.index')
                        ->with('success','Role created successfully.');
    }

    public function show(Role $role)
    {
        $permission = Permission::allPermission();
        $this->setTitle('Detail Role');
        $this->pushBreadcrumb(['Detail Role' => '#']);
        return $this->render('modules.roles.show', [
            'record' => $role,
            'permission' => $permission,
            'rolePermissions' => $role->perms()
        ]);
    }

    public function edit(Role $role)
    {
        $permission = Permission::allPermission();
        $this->setTitle('Change Role');
        $this->pushBreadcrumb(['Change Role' => '#']);
        return $this->render('modules.roles.edit', [
            'record' => $role,
            'permission' => $permission,
            'rolePermissions' => $role->perms()
        ]);
    }

    public function update(RoleRequest $request, Role $role)
    {
        $role->ubah($request);

        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }

    public function destroy(Role $role)
    {
        $role->hapus();

        return redirect()->route('roles.index')
                        ->with('success','Role deleted successfully');
    }
}

resources/views/modules/roles/create.blade.php
@extends('layouts.page')

@section('form')
@if($errors->any())
<div class="callout callout-danger error-message">
  <h4>Whoops!</h4>
  There were some problems with your input : 
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<form action="{{ route('roles.store') }}" method="POST" enctype="multipart/form-data">
  @csrf
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('name') has-error @enderror">
        <label>Name:</label>
        <input type="text" name="name" class="form-control required" placeholder="Name" value="{{ old('name') }}">
        @error('name')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('permission') has-error @enderror">
        <label>Permissions:</label>
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr class="bg-light-blue">
                <th>Name</th>
                <th class="text-center" width="10%">List</th>
                <th class="text-center" width="10%">Create</th>
                <th class="text-center" width="10%">Edit</th>
                <th class="text-center" width="10%">Delete</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Product</td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-list'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-create'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-edit'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-delete'] }}"></td>
              </tr>
              <tr>
                <td>User Management</td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-list'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-create'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-edit'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-delete'] }}"></td>
              </tr>
              <tr>
                <td>Role & Permission</td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-list'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-create'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-edit'] }}"></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-delete'] }}"></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
      <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
    </div>
  </div>
</form>
@endsection

@section('script')
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
@endsection

resources/views/modules/roles/edit.blade.php
@extends('layouts.page')

@section('form')
@if($errors->any())
<div class="callout callout-danger error-message">
  <h4>Whoops!</h4>
  There were some problems with your input : 
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<form action="{{ route('roles.update',$record->id) }}" method="POST" enctype="multipart/form-data">
  @csrf
  @method('PUT')
  <input type="hidden" name="id" value="{{ $record->id }}">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('name') has-error @enderror">
        <label>Name:</label>
        <input type="text" name="name" class="form-control required" placeholder="Name" value="{{ $record->name }}">
        @error('name')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('permission') has-error @enderror">
        <label>Permissions:</label>
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr class="bg-light-blue">
                <th>Name</th>
                <th class="text-center" width="10%">List</th>
                <th class="text-center" width="10%">Create</th>
                <th class="text-center" width="10%">Edit</th>
                <th class="text-center" width="10%">Delete</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Product</td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-list'] }}" @if(in_array($permission['product-list'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-create'] }}" @if(in_array($permission['product-create'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-edit'] }}" @if(in_array($permission['product-edit'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['product-delete'] }}" @if(in_array($permission['product-delete'], $rolePermissions)) {{'checked'}} @endif></td>
              </tr>
              <tr>
                <td>User Management</td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-list'] }}" @if(in_array($permission['user-list'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-create'] }}" @if(in_array($permission['user-create'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-edit'] }}" @if(in_array($permission['user-edit'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['user-delete'] }}" @if(in_array($permission['user-delete'], $rolePermissions)) {{'checked'}} @endif></td>
              </tr>
              <tr>
                <td>Role & Permission</td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-list'] }}" @if(in_array($permission['role-list'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-create'] }}" @if(in_array($permission['role-create'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-edit'] }}" @if(in_array($permission['role-edit'], $rolePermissions)) {{'checked'}} @endif></td>
                <td class="text-center"><input type="checkbox" name="permission[]" value="{{ $permission['role-delete'] }}" @if(in_array($permission['role-delete'], $rolePermissions)) {{'checked'}} @endif></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
      <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
    </div>
  </div>
</form>
@endsection

@section('script')
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
@endsection

resources/views/modules/roles/index.blade.php
@extends('layouts.grid')

@section('filter')
<div class="form-group">
  <input type="text" class="form-control" style="display:none;">
  <input type="text" name="filter[name]" class="form-control" placeholder="Name" title="Name" data-toggle='tooltip'>
</div>
<button type="reset" class="btn btn-default btn-flat btn-reset" title="Reset" data-toggle='tooltip'><i class="fa fa-refresh"></i></button>
<button type="button" class="btn btn-primary btn-flat btn-search" title="Search" data-toggle='tooltip'><i class="fa fa-search"></i></button>
@can('role-create')
<button type="button" class="btn btn-primary btn-flat pull-right btn-create-page" data-url="{{ route('roles.create') }}" title="Create" data-toggle='tooltip'><i class="fa fa-plus"></i> Create Role</button>
@endcan
@endsection

@section('js-filters')
  d.name = $("input[name='filter[name]']").val();
@endsection

resources/views/modules/roles/show.blade.php
@extends('layouts.page')

@section('form')
@if($errors->any())
<div class="callout callout-danger error-message">
  <h4>Whoops!</h4>
  There were some problems with your input : 
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('name') has-error @enderror">
        <label>Name:</label>
        <input type="text" name="name" class="form-control required" placeholder="Name" value="{{ $record->name }}" readonly>
        @error('name')
        <span class="help-block">{{ $message }}</span>
        @enderror
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group @error('permission') has-error @enderror">
        <label>Permissions:</label>
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr class="bg-light-blue">
                <th>Name</th>
                <th class="text-center" width="10%">List</th>
                <th class="text-center" width="10%">Create</th>
                <th class="text-center" width="10%">Edit</th>
                <th class="text-center" width="10%">Delete</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Product</td>
                <td class="text-center">@if(in_array($permission['product-list'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['product-create'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['product-edit'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['product-delete'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
              </tr>
              <tr>
                <td>User Management</td>
                <td class="text-center">@if(in_array($permission['user-list'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['user-create'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['user-edit'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['user-delete'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
              </tr>
              <tr>
                <td>Role & Permission</td>
                <td class="text-center">@if(in_array($permission['role-list'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['role-create'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['role-edit'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
                <td class="text-center">@if(in_array($permission['role-delete'], $rolePermissions)) <i class="fa fa-check text-primary"></i> @endif</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <a href="{{ url()->previous() }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
    </div>
  </div>
@endsection