routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home');
Route::get('page', 'PageController@index')->name('page');
Route::post('ads', 'PageController@ads')->name('ads');
Route::post('message', 'PageController@message')->name('message');
Route::post('subscribe', 'PageController@subscribe')->name('subscribe');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::post('roles/grid', 'RoleController@grid');
    Route::resource('roles','RoleController');
    Route::post('users/grid', 'UserController@grid');
    Route::resource('users','UserController');
    Route::post('products/grid', 'ProductController@grid');
    Route::resource('products','ProductController');
});

resources/views/layouts/partials/aside.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="@if(!is_null(auth()->user()->photopath)) {{ url('storage/'.auth()->user()->photopath) }} @else {{ asset('adminlte/dist/img/user.jpg') }} @endif" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>{{ auth()->user()->name }}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- search form -->
    {{-- <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                <i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form> --}}
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN MENU</li>
      <li><a href="{{ route('home') }}"><i class="fa fa-home"></i> <span>Home</span></a></li>
      <li><a href="{{ route('products.index') }}"><i class="fa fa-briefcase"></i> <span>Product</span></a></li>
      @canany(['user-list', 'role-list'])
      <li class="header">SETTINGS</li>
      @can('user-list')
      <li><a href="{{ route('users.index') }}"><i class="fa fa-users"></i> <span>User Management</span></a></li>
      @endcan
      @can('role-list')
      <li><a href="{{ route('roles.index') }}"><i class="fa fa-book"></i> <span>Role & Permission</span></a></li>
      @endcan
      @endcan
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

resources/views/layouts/partials/content-header.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    {{ $title ?? '' }}
    <small>{{ $subtitle ?? '' }}</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}" title="Go to home" data-toggle='tooltip'><i class="fa fa-home"></i></a></li>
    <?php $i=1;$last=count($breadcrumb);?>
    @foreach( $breadcrumb as $name => $link )
      @if( $i++ != $last )
        <li><a href="{{ $link }}">{{ $name }}</a></li>
      @else
        <li class="active">{{ $name }}</li>
      @endif
    @endforeach        
  </ol>
</section>

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.1
  </div>
  <strong>Copyright &copy; 2020 @if(date('Y')>2020) {{ "-" . date('Y') }} @endif <a href="https://www.lyzaxx-systema.com/" target="_blank">Lyzaxx Systema</a>.</strong> All rights
  reserved.
</footer>

resources/views/layouts/partials/header-navbar.blade.php
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button" title="Expand full width">
    <span class="sr-only">Toggle navigation</span>
  </a>
  <!-- Navbar Right Menu -->
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- Notifications: style can be found in dropdown.less -->
      <li class="dropdown notifications-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Notifications">
          <i class="fa fa-bell-o"></i>
          <span class="label label-warning">10</span>
        </a>
        <ul class="dropdown-menu">
          <li class="header">You have 10 notifications</li>
          <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
              <li>
                <a href="#">
                  <i class="fa fa-users text-aqua"></i> 5 new members joined today
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                  page and may cause design problems
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-users text-red"></i> 5 new members joined
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-user text-red"></i> You changed your username
                </a>
              </li>
            </ul>
          </li>
          <li class="footer"><a href="#">View all</a></li>
        </ul>
      </li>
      <!-- User Account: style can be found in dropdown.less -->
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Open user panel">
          <img src="@if(!is_null(auth()->user()->photopath)) {{ url('storage/'.auth()->user()->photopath) }} @else {{ asset('adminlte/dist/img/user.jpg') }} @endif" class="user-image" alt="User Image">
          <span class="hidden-xs">{{ auth()->user()->name }}</span>
        </a>
        <ul class="dropdown-menu">
          <!-- User image -->
          <li class="user-header">
            <img src="@if(!is_null(auth()->user()->photopath)) {{ url('storage/'.auth()->user()->photopath) }} @else {{ asset('adminlte/dist/img/user.jpg') }} @endif" class="img-circle" alt="User Image">

            <p>
              {{ auth()->user()->name }} - {{ auth()->user()->roles[0]->name }}
              <small>Member since {{ Carbon\Carbon::parse(auth()->user()->created_at)->format('M, Y') }}</small>
            </p>
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <div class="pull-left">
              <a href="{{ route('users.edit',auth()->user()->id) }}" class="btn btn-default btn-flat" title="Go to your profile" data-toggle='tooltip'>Profile</a>
            </div>
            <div class="pull-right">
              <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" title="Sign out" data-toggle='tooltip'>Sign out</a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>

</nav>